//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementAngularProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class status_tbl
    {
        public int st_id { get; set; }
        public string st_name { get; set; }
    }
}
